CREATE TABLE [dbo].[myobDataFileInformation] (
    [CompanyName]                       VARCHAR (42)  NULL,
    [Address]                           VARCHAR (255) NULL,
    [Phone]                             VARCHAR (20)  NULL,
    [FaxNumber]                         VARCHAR (20)  NULL,
    [Email]                             VARCHAR (255) NULL,
    [ABN]                               VARCHAR (14)  NULL,
    [ABNBranch]                         VARCHAR (11)  NULL,
    [ACN]                               VARCHAR (19)  NULL,
    [GSTRegistrationNumber]             VARCHAR (19)  NULL,
    [SalesTaxNumber]                    VARCHAR (19)  NULL,
    [CompanyRegistrationNumber]         VARCHAR (19)  NULL,
    [CurrentFinancialYear]              SMALLINT      NULL,
    [LastMonthInFinancialYear]          SMALLINT      NULL,
    [ConversionDate]                    DATE          NULL,
    [PeriodsPerYear]                    SMALLINT      NULL,
    [PayeeNumber]                       VARCHAR (8)   NULL,
    [BankCode]                          VARCHAR (3)   NULL,
    [BankID]                            VARCHAR (6)   NULL,
    [BSBCode]                           VARCHAR (7)   NULL,
    [BankAccountNumber]                 VARCHAR (9)   NULL,
    [BankAccountName]                   VARCHAR (26)  NULL,
    [IsSelfBalancing]                   VARCHAR (3)   NULL,
    [StatementParticulars]              VARCHAR (12)  NULL,
    [StatementCode]                     VARCHAR (12)  NULL,
    [StatementReference]                VARCHAR (12)  NULL,
    [LastPurgeDate]                     DATE          NULL,
    [LastBackupDate]                    DATE          NULL,
    [DatabaseVersion]                   VARCHAR (8)   NULL,
    [DataFileCountry]                   VARCHAR (3)   NULL,
    [DriverBuildNumber]                 INT           NULL,
    [SerialNumber]                      VARCHAR (12)  NULL,
    [CompanyFileNumber]                 VARCHAR (12)  NULL,
    [UseRetailManagerLink]              VARCHAR (1)   NULL,
    [UseMultipleCurrencies]             VARCHAR (1)   NULL,
    [UseCostCentres]                    VARCHAR (1)   NULL,
    [CostCentresRequired]               VARCHAR (1)   NULL,
    [UseSimplifiedTaxSystem]            VARCHAR (3)   NULL,
    [SimplifiedTaxSystemDate]           DATE          NULL,
    [UseSmallBusinessEntityConcession]  VARCHAR (3)   NULL,
    [SmallBusinessEntityConcessionDate] DATE          NULL,
    [UseDailyAgeing]                    VARCHAR (1)   NULL,
    [FirstAgeingPeriod]                 SMALLINT      NULL,
    [SecondAgeingPeriod]                SMALLINT      NULL,
    [ThirdAgeingPeriod]                 SMALLINT      NULL,
    [IdentifyAgeByName]                 VARCHAR (1)   NULL,
    [LockPeriodIsActive]                VARCHAR (1)   NULL,
    [LockPeriodDate]                    DATE          NULL,
    [LockThirteenthPeriod]              VARCHAR (1)   NULL,
    [DefaultCustomerTermsID]            INT           NULL,
    [DefaultCustomerPriceLevelID]       VARCHAR (3)   NULL,
    [DefaultCustomerTaxCodeID]          INT           NULL,
    [DefaultUseCustomerTaxCode]         VARCHAR (1)   NULL,
    [DefaultCustomerFreightTaxCodeID]   INT           NULL,
    [DefaultSupplierTaxCodeID]          INT           NULL,
    [DefaultUseSupplierTaxCode]         VARCHAR (1)   NULL,
    [DefaultSupplierFreightTaxCodeID]   INT           NULL,
    [DefaultCustomerCreditLimit]        FLOAT (53)    NULL,
    [DefaultSupplierTermsID]            INT           NULL,
    [DefaultSupplierCreditLimit]        FLOAT (53)    NULL,
    [InvoiceSubject]                    VARCHAR (255) NULL,
    [InvoiceMessage]                    VARCHAR (255) NULL,
    [IncludeInvoiceNumber]              VARCHAR (1)   NULL,
    [InvoiceQuoteSubject]               VARCHAR (255) NULL,
    [InvoiceQuoteMessage]               VARCHAR (255) NULL,
    [IncludeInvoiceQuoteNumber]         VARCHAR (1)   NULL,
    [InvoiceOrderSubject]               VARCHAR (255) NULL,
    [InvoiceOrderMessage]               VARCHAR (255) NULL,
    [IncludeInvoiceOrderNumber]         VARCHAR (1)   NULL,
    [PurchaseSubject]                   VARCHAR (255) NULL,
    [PurchaseMessage]                   VARCHAR (255) NULL,
    [IncludePurchaseNumber]             VARCHAR (1)   NULL,
    [PurchaseQuoteSubject]              VARCHAR (255) NULL,
    [PurchaseQuoteMessage]              VARCHAR (255) NULL,
    [IncludePurchaseQuoteNumber]        VARCHAR (1)   NULL,
    [PurchaseOrderSubject]              VARCHAR (255) NULL,
    [PurchaseOrderMessage]              VARCHAR (255) NULL,
    [IncludePurchaseOrderNumber]        VARCHAR (1)   NULL,
    [StatementSubject]                  VARCHAR (255) NULL,
    [StatementMessage]                  VARCHAR (255) NULL,
    [UseAuditTracking]                  VARCHAR (1)   NULL,
    [UseCreditLimitWarning]             VARCHAR (1)   NULL,
    [LimitTypeID]                       VARCHAR (1)   NULL,
    [UseStandardCost]                   VARCHAR (1)   NULL,
    [UseReceivablesFreight]             VARCHAR (1)   NULL,
    [UseReceivablesDeposits]            VARCHAR (1)   NULL,
    [UseReceivablesDiscounts]           VARCHAR (1)   NULL,
    [UseReceivablesLateFees]            VARCHAR (1)   NULL,
    [UsePayablesInventory]              VARCHAR (1)   NULL,
    [UsePayablesFreight]                VARCHAR (1)   NULL,
    [UsePayablesDeposits]               VARCHAR (1)   NULL,
    [UsePayablesDiscounts]              VARCHAR (1)   NULL,
    [UsePayablesLateFees]               VARCHAR (1)   NULL,
    [PaymentSubject]                    VARCHAR (255) NULL,
    [PaymentMessage]                    VARCHAR (255) NULL,
    [ChangeControl]                     VARCHAR (15)  NULL,
    [EntityID]                          SMALLINT      NULL
);

